#!/usr/bin/env bash
set -euo pipefail

# Codex Cloud setup script for testing this registry in a fresh container.
# If this repo becomes private, configure AGENTIC_REGISTRY_GITHUB_TOKEN as a
# Codex Cloud secret. Secrets are available during setup only.

CURRENT_REF="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ -z "$CURRENT_REF" ] || [ "$CURRENT_REF" = "HEAD" ]; then
  CURRENT_REF="main"
fi

REGISTRY_REPO="${AGENTIC_REGISTRY_REPO:-elliot-d-kim/agentic-registry}"
REGISTRY_REF="${AGENTIC_REGISTRY_REF:-$CURRENT_REF}"
REGISTRY_ROOT="${AGENTIC_REGISTRY_ROOT:-$HOME/.codex-cloud/agentic-registry}"
PROJECT_ROOT="$(pwd)"

rm -rf "$REGISTRY_ROOT"
mkdir -p "$(dirname "$REGISTRY_ROOT")"

if [ -n "${AGENTIC_REGISTRY_GITHUB_TOKEN:-}" ]; then
  git clone --depth 1 --branch "$REGISTRY_REF" \
    "https://x-access-token:${AGENTIC_REGISTRY_GITHUB_TOKEN}@github.com/${REGISTRY_REPO}.git" \
    "$REGISTRY_ROOT"
  git -C "$REGISTRY_ROOT" remote set-url origin "https://github.com/${REGISTRY_REPO}.git"
else
  git clone --depth 1 --branch "$REGISTRY_REF" \
    "https://github.com/${REGISTRY_REPO}.git" \
    "$REGISTRY_ROOT"
fi

if [ -d "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain" ]; then
  mkdir -p "$HOME/.codex/skills"
  rm -rf "$HOME/.codex/skills/repo-brain"
  cp -R "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain" "$HOME/.codex/skills/repo-brain"
fi

mkdir -p "$HOME/.codex-cloud"
printf 'export AGENTIC_REGISTRY_ROOT=%q\n' "$REGISTRY_ROOT" > "$HOME/.codex-cloud/agentic-registry.env"
grep -q "agentic-registry.env" "$HOME/.bashrc" 2>/dev/null || {
  printf '\n[ -f "$HOME/.codex-cloud/agentic-registry.env" ] && . "$HOME/.codex-cloud/agentic-registry.env"\n' >> "$HOME/.bashrc"
}

mkdir -p "$PROJECT_ROOT/.codex-cloud"
STATUS_FILE="$PROJECT_ROOT/.codex-cloud/bootstrap-status.md"
{
  printf '# Codex Cloud Bootstrap Status\n\n'
  printf 'Generated by setup script.\n\n'
  printf 'Registry repo: `%s`\n\n' "$REGISTRY_REPO"
  printf 'Registry ref: `%s`\n\n' "$REGISTRY_REF"
  printf 'Registry root: `%s`\n\n' "$REGISTRY_ROOT"
  printf 'AGENTIC_REGISTRY_ROOT configured before setup: `%s`\n\n' "${AGENTIC_REGISTRY_ROOT:-}"
  printf '## Repo Brain Skill\n\n'
  if [ -f "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain/SKILL.md" ]; then
    printf -- '- Found `%s`\n' "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain/SKILL.md"
  fi
  if [ -f "$HOME/.codex/skills/repo-brain/SKILL.md" ]; then
    printf -- '- Found `%s`\n' "$HOME/.codex/skills/repo-brain/SKILL.md"
  fi
} > "$STATUS_FILE"
