#!/usr/bin/env bash
set -euo pipefail

# Codex Cloud setup-script snippet.
# Configure the secret AGENTIC_REGISTRY_GITHUB_TOKEN only when the registry or
# plugin repos are private. Secrets are available during setup only and are
# removed before the agent phase.

REGISTRY_REPO="${AGENTIC_REGISTRY_REPO:-elliot-d-kim/agentic-registry}"
REGISTRY_REF="${AGENTIC_REGISTRY_REF:-main}"
REGISTRY_ROOT="${AGENTIC_REGISTRY_ROOT:-$HOME/.codex-cloud/agentic-registry}"
PROJECT_ROOT="$(pwd)"

rm -rf "$REGISTRY_ROOT"
mkdir -p "$(dirname "$REGISTRY_ROOT")"

if [ -n "${AGENTIC_REGISTRY_GITHUB_TOKEN:-}" ]; then
  git clone --depth 1 --branch "$REGISTRY_REF" \
    "https://x-access-token:${AGENTIC_REGISTRY_GITHUB_TOKEN}@github.com/${REGISTRY_REPO}.git" \
    "$REGISTRY_ROOT"
  git -C "$REGISTRY_ROOT" remote set-url origin "https://github.com/${REGISTRY_REPO}.git"
else
  git clone --depth 1 --branch "$REGISTRY_REF" \
    "https://github.com/${REGISTRY_REPO}.git" \
    "$REGISTRY_ROOT"
fi

# Best-effort skill fallback. This does not rely on plugin activation; it makes
# bundled skills readable to the agent if Codex Cloud does not load arbitrary
# plugin marketplace state.
if [ -d "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain" ]; then
  mkdir -p "$HOME/.codex/skills"
  rm -rf "$HOME/.codex/skills/repo-brain"
  cp -R "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain" "$HOME/.codex/skills/repo-brain"
fi

# Persist the path for interactive shells and hook scripts in the agent phase.
# Configure AGENTIC_REGISTRY_ROOT in the Codex Cloud environment settings when
# the agent itself must see it as a normal environment variable.
mkdir -p "$HOME/.codex-cloud"
printf 'export AGENTIC_REGISTRY_ROOT=%q\n' "$REGISTRY_ROOT" > "$HOME/.codex-cloud/agentic-registry.env"
grep -q "agentic-registry.env" "$HOME/.bashrc" 2>/dev/null || {
  printf '\n[ -f "$HOME/.codex-cloud/agentic-registry.env" ] && . "$HOME/.codex-cloud/agentic-registry.env"\n' >> "$HOME/.bashrc"
}

# Write status during setup so diagnostics do not depend on repo-local hook
# trust in a fresh cloud container.
mkdir -p "$PROJECT_ROOT/.codex-cloud"
STATUS_FILE="$PROJECT_ROOT/.codex-cloud/bootstrap-status.md"
{
  printf '# Codex Cloud Bootstrap Status\n\n'
  printf 'Generated by setup script.\n\n'
  printf 'Registry repo: `%s`\n\n' "$REGISTRY_REPO"
  printf 'Registry ref: `%s`\n\n' "$REGISTRY_REF"
  printf 'Registry root: `%s`\n\n' "$REGISTRY_ROOT"
  printf 'AGENTIC_REGISTRY_ROOT configured before setup: `%s`\n\n' "${AGENTIC_REGISTRY_ROOT:-}"
  printf '## Repo Brain Skill\n\n'
  if [ -f "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain/SKILL.md" ]; then
    printf -- '- Found `%s`\n' "$REGISTRY_ROOT/plugins/repo-brain/skills/repo-brain/SKILL.md"
  fi
  if [ -f "$HOME/.codex/skills/repo-brain/SKILL.md" ]; then
    printf -- '- Found `%s`\n' "$HOME/.codex/skills/repo-brain/SKILL.md"
  fi
} > "$STATUS_FILE"
